version: "3.7"

services:
  php-cli:
#    image: php:7.4-cli
#    image: php:8.0-cli
#    image: php:8.1-cli
#    image: php:8.2-cli
    image: php:8.3-cli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      XDEBUG_MODE: coverage
      ENVII_ENV: "{{.Node.Hostname}}"
      TZ: America/New_York
    command: [
        'bash','-c', "docker-php-ext-install mysqli pdo pdo_mysql && /var/www/html/tests/codeception/bin/yii migrate --interactive=0 && sleep infinity"
    ]
    networks:
      - testnet

  db:
#    image: mysql:5.7
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      TZ: America/New_York
    networks:
      - testnet
    configs:
      - source: db_init
        target: /docker-entrypoint-initdb.d/swivel_init.sql
    secrets:
      - db_root_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  testnet:

secrets:
  db_root_password:
    file: ./tests/codeception/_data/db_root_password.txt

configs:
  db_init:
    file: ./tests/codeception/_data/schema_init.sql
